-- @description nvk_ICONS
-- @author nvk
-- @version 1.0
-- @changelog
--   1.0 Initial Release
-- @link
--   Store Page https://audioikons.com/
-- @about
--   # nvk_ICONS
--
--   Custom nvk toolbar icons by Øivind Rosvold. Get more colors and other great icons from https://audioikons.com/
-- @provides
--  [data] toolbar_icons/**/*.png